# https://taskfile.dev
version: "3"

tasks:

  default:
    desc: Prints this message
    cmds:
      - cmd: task --list-all

  docs:
    desc: Builds documentation using ocamldoc
    preconditions:
      - command -v ocamldoc
    cmds:
      - cmd: ocamldoc -html -d docs bin/main.ml
    silent: true

  test:
    desc: Runs the tests in the 'tests' directory
    preconditions:
      - command -v dune
    deps:
      - task: build
    cmds:
      - cmd: dune runtest {{.CLI_ARGS}}

  test:watch:
    desc: Continuously runs the tests in the 'tests' directory
    ignore_error: true
    sources:
      - lib/**/*.ml
      - test/**/*.ml
    preconditions:
      - command -v dune
    deps:
      - task: build
    cmds:
      - cmd: dune runtest --watch {{.CLI_ARGS}}

  build:
    desc: Builds the project
    preconditions:
      - command -v dune
    cmds:
      - cmd: dune build

  build:release:
    desc: Builds a release version the project
    preconditions:
      - command -v dune
    cmds:
      - cmd: dune build --release

  run:
    desc: Runs the project
    preconditions:
      - command -v dune
    deps:
      - task: build
    cmds:
      - cmd: dune exec -- ./bin/main.exe {{.CLI_ARGS}}

  repl:
    desc: Opens a REPL for the project
    interactive: true
    preconditions:
      - command -v dune
      - command -v utop
    cmds:
      - cmd: dune utop

  git:hooks:
    desc: sets up the githooks for the project
    cmd: git config core.hooksPath .githooks
